#! /bin/sh

bspc config border_width        2
bspc config window_gap         12
bspc config -m Virtual1 top_padding 16

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_by_distance     true
bspc config focus_follows_pointer true

bspc monitor Virtual1 -d I II III IV V VI VII VIII IX X

bspc rule -a Gimp desktop=^8 follow=on state=floating
bspc rule -a Chromium desktop=^2
bspc rule -a mpv state=floating
bspc rule -a display state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

/home/kalebo/.config/bspwm/autostart &
