#! /bin/sh

bspc config border_width        2
bspc config window_gap         12
bspc config -m VGA-1 top_padding 16

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_by_distance     true
bspc config focus_follows_pointer true

bspc monitor VGA-1 -d I II III IV V
bspc monitor VGA-2 -d VI VII VIII IX X

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Chromium desktop=^2
bspc rule -a mpv floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
